---
- hosts: all
  remote_user: "{{ansible_user}}"
  tasks:
    - name: Ntp
      command: "{{ item }}"
      with_items:
        - sudo systemctl enable ntpd
        - sudo service ntpd start

# play book
# ansible-playbook playbook.yml

# play at task
# ansible-playbook playbook.yml --start-at-task="genconf"