server:
  port: 8761

spring:
  application:
      name: uengine-eureka-server
  profiles:
    active: "dev"

---
spring:
  profiles: dev

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: docker

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: ${HOST}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${HOST}:${PORT}/eureka/
