---
vcap:
  services:
    db:
      external: "@host.db@:10002"
      internal: "marathon-lb-internal.marathon.mesos:10002"
    iam:
      external: "@host.iam@"
      internal: "marathon-lb-internal.marathon.mesos:10003"
    uengine-cloud-config:
      external: "@host.config@"
      internal: "marathon-lb-internal.marathon.mesos:10000"
    eureka-server:
      external: "@host.eureka-server@"
      internal: "marathon-lb-internal.marathon.mesos:10001"
    uengine-cloud-server:
      external: "@host.cloud-server@"
      internal: "marathon-lb-internal.marathon.mesos:10005"
    uengine-cloud-ui:
      external: "@host.cloud-ui@"
      internal: "marathon-lb-internal.marathon.mesos:10006"
    uengine-nexus:
      external: "@host.nexus@"
      internal: "marathon-lb-internal.marathon.mesos:10007"
    kafka:
      external: "@host.kafka@:9092"
      internal: "broker.kafka.l4lb.thisdcos.directory:9092"
    redis:
      external: "@host.redis@:6379"
      internal: "marathon-lb-internal.marathon.mesos:6379"
