---
vcap:
  services:
    db:
      external: "db.pas-mini.io:10002"
      internal: "marathon-lb-internal.marathon.mesos:10002"
    iam:
      external: "iam.pas-mini.io"
      internal: "iam.pas-mini.io:10003"
    uengine-cloud-config:
      external: "config.pas-mini.io"
      internal: "marathon-lb-internal.marathon.mesos:10000"
    eureka-server:
      external: "eureka-server.pas-mini.io"
      internal: "marathon-lb-internal.marathon.mesos:10001"
    uengine-cloud-server:
      external: "cloud-server.pas-mini.io"
      internal: "marathon-lb-internal.marathon.mesos:10005"
    uengine-cloud-ui:
      external: "cloud.pas-mini.io"
      internal: "marathon-lb-internal.marathon.mesos:10006"
