---
ip_detect_path: "genconf/ip-detect"
cluster_name: "uEngine"
oauth_enabled: true
resolvers:
- "121.88.255.50"
- "121.88.255.49"
ssh_port: 22
master_discovery: "static"
ip_detect_public_filename: "genconf/ip-detect"
process_timeout: 10000
exhibitor_storage_backend: "static"
public_agent_list:
- "192.168.0.11"
bootstrap_url: "file:///opt/dcos_install_tmp"
agent_list:
- "192.168.0.13"
- "192.168.0.15"
- "192.168.0.16"
- "192.168.0.17"
- "192.168.0.18"
- "192.168.0.21"
- "192.168.0.42"
telemetry_enabled: true
ssh_key_path: "genconf/ssh_key"
master_list:
- "192.168.0.8"
- "192.168.0.9"
- "192.168.0.10"
ssh_user: "centos"
mesos_max_completed_tasks_per_framework: 10
