title: 
server.public.master: 58.140.91.67:8081
server.public.public: 58.140.91.67

db.ip: 192.168.0.13
db.database: uengine
db.password: my-secret-pw

host.default: pasmini.io
host.registry.package: darkgodarkgo
host.registry.private: gitlab.pasmini.io:5000
host.registry.public: gitlab.pasmini.io:5000
host.db: db.pasmini.io
host.gitlab: gitlab.pasmini.io
host.iam: iam.pasmini.io
host.config: 192.168.0.11:10000
host.eureka-server: eureka-server.pasmini.io
host.cloud-server: cloud-server.pasmini.io
host.cloud-ui: cloud.pasmini.io
host.nexus: nexus.pasmini.io

iam.port: 80
iam.client-key: my-client-key
iam.client-secret: my-client-secret
iam.admin.username: admin
iam.admin.password: admin
iam.access-token-lifetime: 7200
iam.mail.host: smtp.gmail.com
iam.mail.username: sppark@uengine.org
iam.mail.password: 
iam.mail.port: 587
iam.mail.smtp-auth: true
iam.mail.smtp-starttls-enable: true
iam.mail.from-address: sppark@uengine.org
iam.mail.from-name: uengine

dcos.token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkYXJrZ29kYXJrZ29AZ21haWwuY29tIiwiZXhwIjozMTI1NTQ4ODM3MTEuNzkzOX0.NCDPD4HuR8SLMw8T_6lr2QTQ75_E7ppvYIqgaPeWX4s

gitlab.root.username: root
gitlab.root.password: adminadmin
gitlab.root.token: -arWnfRY7S4h6oyRthNy
gitlab.config-repo.projectId: 94
gitlab.config-repo.deployment-path: /deployment
gitlab.config-repo.template-path: /template

nexus.ip: 192.168.0.13
nexus.username: admin
nexus.password: admin123
nexus.mvn.public: http://nexus.pasmini.io/nexus/content/groups/public/
nexus.mvn.release: http://nexus.pasmini.io/nexus/content/repositories/releases/
nexus.mvn.snapshot: http://nexus.pasmini.io/nexus/content/repositories/snapshots/
nexus.npm.public: http://nexus.pasmini.io/nexus/content/groups/npm/
nexus.npm.private: http://nexus.pasmini.io/nexus/content/repositories/npm-private/

pinpoint.use: false
pinpoint.agent-path: 
pinpoint.web: 
pinpoint.collector.ip: 
pinpoint.collector.tcp-port: 
pinpoint.collector.stat-port: 
pinpoint.collector.span-port: 

elk.elasticsearch.private: 
elk.elasticsearch.web: 
elk.kibana.private: 
elk.kibana.web: 
elk.kibana.dashboard-id.app-log: uengine-app-log
elk.kibana.dashboard-id.docker-metric: uengine-doker-metric
elk.kibana.dashboard-id.system-metric: Metricbeat-system-overview








