# SSH and Resolve.conf part
cluster_name: uEngine
ansible_user: centos
ansible_ssh_private_key_file: /home/centos/dcos-key.pem
ssh_port: 22
resolvers:
- 121.88.255.50
- 121.88.255.49
dns_search:

# Server list part
server:
  private:
    bootstrap: 192.168.0.19
    gitlab: 192.168.0.31
    ci:
    public: 192.168.0.11

    master:
      master1: 192.168.0.8
      master2: 192.168.0.9
      master3: 192.168.0.10

    agent:
      agent1: 192.168.0.13
      agent2: 192.168.0.15
      agent3: 192.168.0.16
      agent4: 192.168.0.17
      agent5: 192.168.0.18
      agent6: 192.168.0.21
      agent7: 192.168.0.42

    add-agent:
    gracefully-remove-agent:
    uninstall:

  public:
    # Choice one of your master's public ip
    master: 58.140.91.67:8081
    # Your public node's public ip
    public: 58.140.91.67

# DB part
db:
  ip: 192.168.0.13
  database: uengine
  password: my-secret-pw

# Domain part
host:
  registry:
    package: darkgodarkgo
    private: gitlab.pasmini.io:5000
    public: gitlab.pasmini.io:5000
  db: db.pasmini.io
  gitlab: gitlab.pasmini.io
  iam: iam.pasmini.io
  eureka-server: eureka-server.pasmini.io
  cloud-server: cloud-server.pasmini.io
  cloud-ui: cloud.pasmini.io

# Security(IAM) part
iam:
  port: 80
  client-key: my-client-key
  client-secret: my-client-secret
  admin:
    username: admin
    password: admin
  access-token-lifetime: 7200
  mail:
    host: smtp.gmail.com
    username: sppark@uengine.org
    password: !gosu23546
    port: 587
    smtp-auth: true
    smtp-starttls-enable: true
    from-address: sppark@uengine.org
    from-name: uengine

# Cloud package part
# Fill out those properties after install DC/OS cluster && Gitlab
# Then, you should re-command "mvn clean install exec:java package"
dcos:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkYXJrZ29kYXJrZ29AZ21haWwuY29tIiwiZXhwIjozMTI1NTQ4ODM3MTEuNzkzOX0.NCDPD4HuR8SLMw8T_6lr2QTQ75_E7ppvYIqgaPeWX4s

gitlab:
  root:
    username: root
    password: adminadmin
    token: -arWnfRY7S4h6oyRthNy
  config-repo:
    projectId: 94
    deployment-path: /deployment
    template-path: /template