---
# Sample Zuul configuration

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  addProxyHeaders: true

  # Decides to check the token.
  iam-authentication: true

  # Key to determine if the token's signature is correct.
  # It must be the same key that IAM used to issue the token.
  # Copy and paste from your IAM's iam.jwt.key
  iam-jwt-key: my-jwt-encrypt-key-my-jwt-encrypt-key

  # 메타데이터 암호화 키
  metadata-encoder-secret1: Bar12345Bar12345
  metadata-encoder-secret2: ThisIsASecretKet

  # 복호화 할 메타데이터 필드.
  secure-metadata-fields:
    - "$.gitlabToken"

  routes:
    order:
      path: /orders/**
      serviceId: order-service
      stripPrefix: false
      # List of scopes needed for this path
      iam-scopes:
        - guest/GET
        - catalog-order/PUT-PATCH-POST-DELETE

    # If no iam-scopes, all request will be passed.
    customer:
      path: /customers/**
      serviceId: customer-service
      stripPrefix: false


    item:
      path: /items/**
      serviceId: order-service
      stripPrefix: false
      iam-scopes:
        - guest/GET
        - catalog-manage/PUT-PATCH-POST-DELETE