---
- hosts: public:agent:add-agent
  remote_user: "{{ansible_user}}"
  tasks:
    - name: pinpoint agent copy
      become: true
      become_method: sudo
      copy:
        src: ./pinpoint-agent
        dest: /
        owner: root
        group: root
        mode: 0777