---
- hosts: public:agent
  remote_user: "{{ansible_user}}"
  tasks:
    - name: Update MESOS_CGROUPS_ENABLE_CFS
      command: "{{ item }}"
      with_items:
        - sudo sed -i 's/MESOS_CGROUPS_ENABLE_CFS=true/MESOS_CGROUPS_ENABLE_CFS=false/g' /opt/mesosphere/etc/mesos-slave-common

- hosts: agent
  remote_user: "{{ansible_user}}"
  tasks:
    - name: Agent restart
      command: "{{ item }}"
      with_items:
        - sudo systemctl restart dcos-mesos-slave

- hosts: public
  remote_user: "{{ansible_user}}"
  tasks:
    - name: Public restart
      command: "{{ item }}"
      with_items:
        - sudo systemctl restart dcos-mesos-slave-public