---
- hosts: all
  remote_user: "{{ansible_user}}"
  tasks:
    - name: Host file copy
      become: true
      become_method: sudo
      copy:
        src: ./hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
    - name: Docker util install
      command: "{{ item }}"
      with_items:
        - sudo yum remove docker \
                  docker-common \
                  docker-selinux \
                  docker-engine
        - sudo yum install -y yum-utils \
          device-mapper-persistent-data \
          lvm2

    - name: Docker repository ready
      become: true
      become_method: sudo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      async: 60
      poll: 5

    - name: Yum update
      command: "{{ item }}"
      with_items:
        - sudo yum update -y

    - name: Docker install
      command: "{{ item }}"
      with_items:
        - sudo yum install docker-ce -y

    - name: Utils Install
      command: "{{ item }}"
      with_items:
        - sudo yum install -y ntp tar xz unzip curl ipset bind-utils
        - sudo sed -i s/SELINUX=enforcing/SELINUX=permissive/g /etc/selinux/config
        - sudo yum install haveged -y
        - sudo chkconfig haveged on

    - name: Firewalld off
      command: "{{ item }}"
      with_items:
        - sudo systemctl stop firewalld
        - sudo systemctl disable firewalld
      ignore_errors: True

    - name: Ntp
      command: "{{ item }}"
      with_items:
        - sudo systemctl enable ntpd
        - sudo service ntpd start

    - name: Group add
      command: "{{ item }}"
      with_items:
        - sudo groupadd nogroup
        - sudo groupadd docker
      ignore_errors: True


- hosts: master:public:agent:gitlab:ci
  remote_user: "{{ansible_user}}"
  tasks:
    - name: Restart machine
      shell: sleep 2 && reboot
      async: 1
      poll: 0
      ignore_errors: true
      become: true
      become_method: sudo

    - name: Wait 600 seconds, but only start checking after 10 seconds
      wait_for_connection:
        delay: 10
        timeout: 600

- hosts: all
  remote_user: "{{ansible_user}}"
  tasks:
    - block:
      - name: Checking Docker folders
        stat:
         path: "{{item}}"
        register: folder_stats
        with_items:
        - ["/etc/docker/"]
      - name: Creating Docker folders
        become: true
        become_method: sudo
        file:
         path: "{{item.item}}"
         state: directory
         mode: 0644
         group: root
         owner: root
        when: item.stat.exists == false
        with_items:
        - "{{folder_stats.results}}"

    - name: Docker devicemapper
      become: true
      become_method: sudo
      copy:
        content: |
          {"storage-driver": "vfs","insecure-registries" : ["{{registry_host}}"]}
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644

    - name: Docker daemon reload
      command: "{{ item }}"
      with_items:
        - sudo systemctl daemon-reload
        - sudo systemctl enable docker
        - sudo systemctl restart docker
      ignore_errors: True

    - name: Docker cadvisor
      command: "{{ item }}"
      with_items:
        - sudo docker run -d --restart always --privileged=true --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --volume=/dev/disk/:/dev/disk:ro --publish=8080:8080 --detach=true --name=cadvisor google/cadvisor:latest

# play book
# ansible-playbook ansible-install.yml

# play at task
# ansible-playbook ansible-install.yml --start-at-task="Docker devicemapper"

# play at task and step
# ansible-playbook ansible-install.yml --step --start-at-task="Docker devicemapper"